using System.Collections.Generic;

namespace WeddingPlanner.DataAccess.Constants
{
	public static class Constants
	{
		public static IDictionary<USState, string> States
			=> new Dictionary<USState, string>
			{
				{USState.AA, "Armed Forces Americas"},
				{USState.AE, "Armed Forces Europe, Middle East, & Canada"},
				{USState.AK, "Alaska"},
				{USState.AL, "Alabama"},
				{USState.AP, "Armed Forces Pacific"},
				{USState.AR, "Arkansas"},
				{USState.AS, "American Samoa"},
				{USState.AZ, "Arizona"},
				{USState.CA, "California"},
				{USState.CO, "Colorado"},
				{USState.CT, "Connecticut"},
				{USState.DC, "District of Columbia"},
				{USState.DE, "Delaware"},
				{USState.FL, "Florida"},
				{USState.FM, "Federated States of Micronesia"},
				{USState.GA, "Georgia"},
				{USState.GU, "Guam"},
				{USState.HI, "Hawaii"},
				{USState.IA, "Iowa"},
				{USState.ID, "Idaho"},
				{USState.IL, "Illinois"},
				{USState.IN, "Indiana"},
				{USState.KS, "Kansas"},
				{USState.KY, "Kentucky"},
				{USState.LA, "Louisiana"},
				{USState.MA, "Massachusetts"},
				{USState.MD, "Maryland"},
				{USState.ME, "Maine"},
				{USState.MH, "Marshall Islands"},
				{USState.MI, "Michigan"},
				{USState.MN, "Minnesota"},
				{USState.MO, "Missouri"},
				{USState.MP, "Northern Mariana Islands"},
				{USState.MS, "Mississippi"},
				{USState.MT, "Montana"},
				{USState.NC, "North Carolina"},
				{USState.ND, "North Dakota"},
				{USState.NE, "Nebraska"},
				{USState.NH, "New Hampshire"},
				{USState.NJ, "New Jersey"},
				{USState.NM, "New Mexico"},
				{USState.NV, "Nevada"},
				{USState.NY, "New York"},
				{USState.OH, "Ohio"},
				{USState.OK, "Oklahoma"},
				{USState.OR, "Oregon"},
				{USState.PA, "Pennsylvania"},
				{USState.PR, "Puerto Rico"},
				{USState.PW, "Palau"},
				{USState.RI, "Rhode Island"},
				{USState.SC, "South Carolina"},
				{USState.SD, "South Dakota"},
				{USState.TN, "Tennessee"},
				{USState.TX, "Texas"},
				{USState.UT, "Utah"},
				{USState.VA, "Virginia"},
				{USState.VI, "Virgin Islands"},
				{USState.VT, "Vermont"},
				{USState.WA, "Washington"},
				{USState.WV, "West Virginia"},
				{USState.WI, "Wisconsin"},
				{USState.WY, "Wyoming"}
			};
	}
}